wordpress:
  image: wordpress:5.6.0-php7.4
  container_name: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - "8080:80"
  environment:
    - WORDPRESS_DB_HOST=mysql
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_PASSWORD=secret
    - WORDPRESS_DB_NAME=wordpress
  volumes:
    - /var/www/html/wordpress:/var/www/html/wordpress
wordpress_db:
  image: mariadb
  container_name: wordpress_db
  environment:
    - MYSQL_ROOT_PASSWORD=secret
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  container_name: phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - "8081:80"
  environment:
    - MYSQL_USERNAME=root
    - MYSQL_ROOT_PASSWORD=secret
